# Defines the local environment configuration for our application
# See: DOCKER.md

version: '1'
services:
  api:
    container_name: libxml-test
    build: .
    environment:
      - APP_ENV=development
    ports:
      - '5000:5000'
